#!/bin/bash

# Tracks
echo '\nNew tracks\n'
curl --verbose \
     --header "Content-type: application/json" \
     --request POST \
     --data @data/tracks/track1.json \
     http://localhost:5000/tracks

curl --verbose \
     --header "Content-type: application/json" \
     --request POST \
     --data @data/tracks/track2.json \
     http://localhost:5000/tracks

curl --verbose \
     --header "Content-type: application/json" \
     --request POST \
     --data @data/tracks/track3.json \
     http://localhost:5000/tracks

echo '\nUpdate track\n'
curl --verbose \
     --header "Content-type: application/json" \
     --request PATCH \
     --data @data/tracks/track_edit.json \
     http://localhost:5000/tracks/3

echo '\nGet track\n'
curl --verbose \
     --header "Content-type: application/json" \
     --request GET \
     http://localhost:5000/tracks/3

echo '\nDelete track\n'
curl --verbose \
     --header "Content-type: application/json" \
     --request DELETE \
     http://localhost:5000/tracks/3

# Playlists
echo '\nNew playlists\n'
curl --verbose \
     --header "Content-type: application/json" \
     --request POST \
     --data @data/playlists/playlist1.json \
     http://localhost:5001/playlists

curl --verbose \
     --header "Content-type: application/json" \
     --request POST \
     --data @data/playlists/playlist2.json \
     http://localhost:5001/playlists

curl --verbose \
     --header "Content-type: application/json" \
     --request POST \
     --data @data/playlists/playlist3.json \
     http://localhost:5001/playlists

echo '\nGet playlist\n'
curl --verbose \
     --header "Content-type: application/json" \
     --request GET \
     http://localhost:5000/playlists/2

echo '\nList all playlists\n'
curl --verbose \
     --header "Content-type: application/json" \
     --request GET \
     http://localhost:5000/playlists/all

echo '\nList all playlists by user\n'
curl --verbose \
     --header "Content-type: application/json" \
     --request GET \
     http://localhost:5000/playlists?creator=username2

echo '\nDelete playlist\n'
curl --verbose \
     --header "Content-type: application/json" \
     --request DELETE \
     http://localhost:5000/playlists/3

# # Users
# curl --verbose \
#      --header "Content-type: application/json" \
#      --request POST \
#      --data @data/sample_user.json \
#      http://localhost:5001/users
# 
# curl --verbose \
#      --header "Content-type: application/json" \
#      --request DELETE \
#      http://localhost:5001/users/3
# 
#      curl --verbose \
#      --header "Content-type: application/json" \
#      --request PUT \
#      --data @data/sample_user.json \
#      http://localhost:5001/users
# 
# curl --verbose \
#      --header "Content-type: application/json" \
#      --request GET \
#      http://localhost:5001/users/3
# 
# 
# # Descriptions
# curl --verbose \
#      --header "Content-type: application/json" \
#      --request POST \
#      --data @data/sample_description.json \
#      http://localhost:5003/descriptions
# 
# curl --verbose \
#      --header "Content-type: application/json" \
#      --request DELETE \
#      http://localhost:5003/descriptions/3
# 
#      curl --verbose \
#      --header "Content-type: application/json" \
#      --request PUT \
#      --data @data/sample_description.json \
#      http://localhost:5003/descriptions
# 
# curl --verbose \
#      --header "Content-type: application/json" \
#      --request GET \
#      http://localhost:5003/descriptions/3

