tracks: FLASK_APP=tracks.py flask run --port 5000
playlist: FLASK_APP=playlists.py flask run --port 5001
users: FLASK_APP=users.py flask run --port 5002
descriptions: FLASK_APP=descriptions.py flask run --port 5003
