tracks: FLASK_APP=tracks.py flask run --port $PORT
playlists: FLASK_APP=playlists.py flask run --port $PORT
users: FLASK_APP=users.py flask run --port $PORT
descriptions: FLASK_APP=descriptions.py flask run --port $PORT
xspf: FLASK_APP=xspf.py flask run --port $PORT
