#!/bin/bash

# Tracks
echo '\nNew tracks\n'
curl --verbose \
     --header "Content-type: application/json" \
     --request POST \
     --data @data/tracks/track1.json \
     http://localhost:5000/tracks

curl --verbose \
     --header "Content-type: application/json" \
     --request POST \
     --data @data/tracks/track2.json \
     http://localhost:5000/tracks

curl --verbose \
     --header "Content-type: application/json" \
     --request POST \
     --data @data/tracks/track3.json \
     http://localhost:5000/tracks

echo '\nUpdate track\n'
curl --verbose \
     --header "Content-type: application/json" \
     --request PATCH \
     --data @data/tracks/track_edit.json \
     http://localhost:5000/tracks/3

echo '\nGet track\n'
curl --verbose \
     --header "Content-type: application/json" \
     --request GET \
     http://localhost:5000/tracks/3

echo '\nDelete track\n'
curl --verbose \
     --header "Content-type: application/json" \
     --request DELETE \
     http://localhost:5000/tracks/3

# Users
echo '\nCreate new users\n'
curl --verbose \
     --header "Content-type: application/json" \
     --request POST \
     --data @data/users/user1.json \
     http://localhost:5002/users

curl --verbose \
     --header "Content-type: application/json" \
     --request POST \
     --data @data/users/user2.json \
     http://localhost:5002/users

curl --verbose \
     --header "Content-type: application/json" \
     --request POST \
     --data @data/users/user3.json \
     http://localhost:5002/users

echo '\nGet user\n'
curl --verbose \
     --header "Content-type: application/json" \
     --request GET \
     http://localhost:5002/users/username1

curl --verbose \
     --header "Content-type: application/json" \
     --request GET \
     http://localhost:5002/users/username2

echo '\nDelete user\n'
curl --verbose \
     --header "Content-type: application/json" \
     --request DELETE \
     http://localhost:5002/users/username3

echo '\nUpdate user password\n'
curl --verbose \
     --header "Content-type: application/json" \
     --request PATCH \
     --data @data/users/user1Update.json \
     http://localhost:5002/users/username1

echo '\nAuthenticate user\n'
curl --verbose \
     --header "Content-type: application/json" \
     --request GET \
     --data @data/users/user1PasswordCheck.json \
     http://localhost:5002/users/authenticate

# Playlists
echo '\nNew playlists\n'
curl --verbose \
     --header "Content-type: application/json" \
     --request POST \
     --data @data/playlists/playlist1.json \
     http://localhost:5001/playlists

curl --verbose \
     --header "Content-type: application/json" \
     --request POST \
     --data @data/playlists/playlist2.json \
     http://localhost:5001/playlists

curl --verbose \
     --header "Content-type: application/json" \
     --request POST \
     --data @data/playlists/playlist3.json \
     http://localhost:5001/playlists

echo '\nGet playlist\n'
curl --verbose \
     --header "Content-type: application/json" \
     --request GET \
     http://localhost:5001/playlists/2

echo '\nList all playlists\n'
curl --verbose \
     --header "Content-type: application/json" \
     --request GET \
     http://localhost:5001/playlists/all

echo '\nList all playlists by user\n'
curl --verbose \
     --header "Content-type: application/json" \
     --request GET \
     http://localhost:5001/playlists?creator=username2

echo '\nDelete playlist\n'
curl --verbose \
     --header "Content-type: application/json" \
     --request DELETE \
     http://localhost:5001/playlists/3

# Descriptions
curl --verbose \
     --header "Content-type: application/json" \
     --request POST \
     --data @data/descriptions/description1.json \
     http://localhost:5003/descriptions

curl --verbose \
     --header "Content-type: application/json" \
     --request POST \
     --data @data/descriptions/description2.json \
     http://localhost:5003/descriptions

curl --verbose \
     --header "Content-type: application/json" \
     --request GET \
     http://localhost:5003/descriptions/1

