#! /bin/env python3

import requests
from pprint import pprint

# USERS
print("\nINSERTING NEW USER")
r = requests.post(
        'http://localhost:8000/users',
        data = {
            "username" : "username1",
            "user_pass" : "peanuts",
            "disp_name" : "iamuser1",
            "email" : "user1@gmail.com",
            "url_homepage" : "user1.com"
        }
)
pprint(r.content)

print("\nINSERTING NEW USER")
r = requests.post(
        'http://localhost:8000/users',
        data = {
            "username" : "username2",
            "user_pass" : "tree",
            "disp_name" : "iamuser2",
            "email" : "user2@gmail.com",
            "url_homepage" : "user2.com"
        }
)
pprint(r.content)

print("\nINSERTING NEW USER")
r = requests.post(
        'http://localhost:8000/users',
        data = {
            "username" : "username3",
            "user_pass" : "apple",
            "disp_name" : "iamuser3",
            "email" : "user3@gmail.com",
            "url_homepage" : 'user3.com'
        }
)
pprint(r.content)

print("\nGET USER")
r = requests.get(
        'http://localhost:8000/users/username1',
)
pprint(r.content)

print("\nGET USER")
r = requests.get(
        'http://localhost:8000/users/username2',
)
pprint(r.content)

print("\nGET USER")
r = requests.get(
        'http://localhost:8000/users/username3',
)
pprint(r.content)

print("\nDELETE USER")
r = requests.delete(
        'http://localhost:8000/users/username3',
)
pprint(r.content)

print("\nUPDATE USER PASSWORD")
r = requests.patch(
        'http://localhost:8000/users/username1',
        data = {
            "user_pass" : "bananafruit"
        }
)
pprint(r.content)

print("\nAUTHENTICATE USER")
r = requests.get(
        'http://localhost:8000/users/authenticate',
        data = {
            "username" : "username1",
            "user_pass" : "bananafruit"
        }
)
pprint(r.content)

# TRACKS
print()
track_ids = []

print('\nNEW TRACK')
r = requests.post(
        'http://localhost:8000/tracks',
        data = {
            "track_title": "bass",
            "album_title": "rock",
            "artist": "Flea",
            "track_length": 2.1,
            "media_file_url": "http://localhost:8000/media/bass.mp3",
            "album_art_url": "https://picsum.photos/id/975/200/200"
        }
)
pprint(r.json())
track_ids.append(r.json()['id'])

print('\nNEW TRACK')
r = requests.post(
        'http://localhost:8000/tracks',
        data = {
            "track_title": "electric guitar",
            "album_title": "rock",
            "artist": "Slash",
            "track_length": 2.1,
            "media_file_url": "http://localhost:8000/media/electric-guitar.mp3",
            "album_art_url": "https://picsum.photos/id/876/200/200"
        }
)
pprint(r.json())
track_ids.append(r.json()['id'])

print('\nNEW TRACK')
r = requests.post(
        'http://localhost:8000/tracks',
        data = {
            "track_title": "harp",
            "album_title": "classy",
            "artist": "Yoyoma",
            "track_length": 2.1,
            "media_file_url": "http://localhost:8000/media/harp.mp3",
            "album_art_url": "https://picsum.photos/id/1062/200/200"
        }
)
pprint(r.json())
track_ids.append(r.json()['id'])

print('\nUPDATE TRACK')
r = requests.patch(
        f'http://localhost:8000/tracks/{track_ids[-1]}',
        data = {
            "track_title": "violin",
            "album_title": "classier",
            "track_length": 3.1,
            "media_file_url": "http://localhost:8000/media/violin.mp3",
        }
)
pprint(r.json())

print('\nGET TRACK')
r = requests.get(
        f'http://localhost:8000/tracks/{track_ids[-1]}',
)
pprint(r.json())

print('\nDELETE TRACK')
r = requests.delete(
        f'http://localhost:8000/tracks/{track_ids[-1]}',
)
pprint(r.json())

print('\nNEW DESCRIPTION')
r = requests.post(
        f'http://localhost:8000/descriptions',
        data = {
            "track_id": track_ids[0],
            "user_name": "username1",
            "description": "this is a track description"
        }
)
pprint(r.json())

print('\nNEW DESCRIPTION')
r = requests.post(
        f'http://localhost:8000/descriptions',
        data = {
            "track_id": track_ids[1],
            "user_name": "username2",
            "description": "this is a track description again"
        }
)
pprint(r.json())

print('\nGET DESCRIPTION')
r = requests.get(
        f'http://localhost:8000/descriptions/{track_ids[0]}',
)
pprint(r.json())
